type User {
  userId: String!
  foodDiary: [FoodDiary] @relation
  fitnessPlan: [FitPlan] @relation
  userData: [UserInputData] @relation
  currentSession: String
  subscriptionType: String!
}

type FoodDiary {
  userId: User!
  type: String!
  time: Int!
  details: String
}

type FitPlan {
  userId: User!
  sessionTitle: String!
  shortTitle: String!
  rating: Int
  notes: String
  cardInfo: [CardInfo]!
}

type CardInfo @embedded{
  cardTitle: String!
  listOfActivities: [Activity]!
}

type Activity @embedded {
  userInputDataId: [String]
  datum: [Float]
  units: [String]
  primary: String!
  secondary: String
  video: String
}

type UserInputData {
  userId: User!
  name: String!
  inputDataUnit: String!
  inputtedData: [UserData]
}

type UserData @embedded {
  sessionId: String!
  shortTitle: String!
  datum: Float!
}

type Query {
  findId(userId: String!): User!
  allUsers: [User!]
}